export const ERROR_CODES: { [index: string]: string } = {
  REQUIRED: '101',

  EMAIL_IS_REQUIRED: '201',
  EMAIL_IS_INVALID: '102',

  PASSWORD_IS_REQUIRED: '202',
  PASSWORD_TOO_SHORT: '105',
  PASSWORDS_NOT_MATCH: '106',

  //API
  API_UNEXPECTED_ERROR: '500',
  API_BAD_CREDENTIALS: '501',
};

export const ERROR_MESSAGES: { [index: string]: string } = {
  [ERROR_CODES.REQUIRED]: 'ERROR.VALIDATION.REQUIRED',
  [ERROR_CODES.EMAIL_IS_REQUIRED]: 'ERROR.VALIDATION.EMAIL.REQUIRED',
  [ERROR_CODES.EMAIL_IS_INVALID]: 'ERROR.VALIDATION.EMAIL.INVALID',
  [ERROR_CODES.PASSWORD_IS_REQUIRED]: 'ERROR.VALIDATION.PASSWORD.REQUIRED',
  [ERROR_CODES.PASSWORD_TOO_SHORT]: 'ERROR.VALIDATION.PASSWORD.TOO_SHORT',
  [ERROR_CODES.API_UNEXPECTED_ERROR]: 'ERROR.API.UNEXPECTED',
  [ERROR_CODES.API_BAD_CREDENTIALS]: 'ERROR.API.BAD_CREDENTIALS',
};
