// flow-typed signature: f11cbb849c4f790c341c37922288026c
// flow-typed version: <<STUB>>/email-remove-unused-css_v^3.0.5/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'email-remove-unused-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'email-remove-unused-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'email-remove-unused-css/dist/email-remove-unused-css.cjs' {
  declare module.exports: any;
}

declare module 'email-remove-unused-css/dist/email-remove-unused-css.esm' {
  declare module.exports: any;
}

declare module 'email-remove-unused-css/dist/email-remove-unused-css.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'email-remove-unused-css/dist/email-remove-unused-css.cjs.js' {
  declare module.exports: $Exports<'email-remove-unused-css/dist/email-remove-unused-css.cjs'>;
}
declare module 'email-remove-unused-css/dist/email-remove-unused-css.esm.js' {
  declare module.exports: $Exports<'email-remove-unused-css/dist/email-remove-unused-css.esm'>;
}
declare module 'email-remove-unused-css/dist/email-remove-unused-css.umd.js' {
  declare module.exports: $Exports<'email-remove-unused-css/dist/email-remove-unused-css.umd'>;
}
