// flow-typed signature: 31afa7c444971a18b6359e60b5c427b8
// flow-typed version: <<STUB>>/p-min-delay_v^2.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-min-delay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-min-delay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-min-delay/index' {
  declare module.exports: $Exports<'p-min-delay'>;
}
declare module 'p-min-delay/index.js' {
  declare module.exports: $Exports<'p-min-delay'>;
}
