// flow-typed signature: cc863ea133dd9c02d38080aec7b9dd16
// flow-typed version: <<STUB>>/pick-react-known-prop_v^0.1.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pick-react-known-prop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pick-react-known-prop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pick-react-known-prop/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pick-react-known-prop/dist/index.js' {
  declare module.exports: $Exports<'pick-react-known-prop/dist/index'>;
}
