// flow-typed signature: 9f36fc55f857bda3632819c53e9a977e
// flow-typed version: <<STUB>>/react-scroll-parallax_v^1.3.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll-parallax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll-parallax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scroll-parallax/__tests__/clamp.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/getParallaxOffsets.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/isElementInView.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/Parallax.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/ParallaxBanner.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/ParallaxController.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/ParallaxProvider.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/parseValueAndUnit.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/propValidation.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/scaleBetween.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/__tests__/testForPassiveScroll.test' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/components/Parallax' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/components/ParallaxBanner' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/components/ParallaxProvider' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/index' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/libs/ParallaxController' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/utils/clamp' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/utils/getParallaxOffsets' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/utils/isElementInView' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/utils/parseValueAndUnit' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/utils/propValidation' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/utils/scaleBetween' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/lib/utils/testForPassiveScroll' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/postcss.config' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/components/Parallax' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/components/ParallaxBanner' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/components/ParallaxProvider' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/index' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/libs/ParallaxController' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/utils/clamp' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/utils/getParallaxOffsets' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/utils/index' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/utils/isElementInView' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/utils/parseValueAndUnit' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/utils/propValidation' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/utils/scaleBetween' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/src/utils/testForPassiveScroll' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/stories/Element/Element' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/stories/Parallax/Parallax.stories' {
  declare module.exports: any;
}

declare module 'react-scroll-parallax/stories/ParallaxBanner/ParallaxBanner.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scroll-parallax/__tests__/clamp.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/clamp.test'>;
}
declare module 'react-scroll-parallax/__tests__/getParallaxOffsets.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/getParallaxOffsets.test'>;
}
declare module 'react-scroll-parallax/__tests__/isElementInView.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/isElementInView.test'>;
}
declare module 'react-scroll-parallax/__tests__/Parallax.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/Parallax.test'>;
}
declare module 'react-scroll-parallax/__tests__/ParallaxBanner.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/ParallaxBanner.test'>;
}
declare module 'react-scroll-parallax/__tests__/ParallaxController.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/ParallaxController.test'>;
}
declare module 'react-scroll-parallax/__tests__/ParallaxProvider.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/ParallaxProvider.test'>;
}
declare module 'react-scroll-parallax/__tests__/parseValueAndUnit.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/parseValueAndUnit.test'>;
}
declare module 'react-scroll-parallax/__tests__/propValidation.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/propValidation.test'>;
}
declare module 'react-scroll-parallax/__tests__/scaleBetween.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/scaleBetween.test'>;
}
declare module 'react-scroll-parallax/__tests__/testForPassiveScroll.test.js' {
  declare module.exports: $Exports<'react-scroll-parallax/__tests__/testForPassiveScroll.test'>;
}
declare module 'react-scroll-parallax/lib/components/Parallax.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/components/Parallax'>;
}
declare module 'react-scroll-parallax/lib/components/ParallaxBanner.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/components/ParallaxBanner'>;
}
declare module 'react-scroll-parallax/lib/components/ParallaxProvider.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/components/ParallaxProvider'>;
}
declare module 'react-scroll-parallax/lib/index.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/index'>;
}
declare module 'react-scroll-parallax/lib/libs/ParallaxController.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/libs/ParallaxController'>;
}
declare module 'react-scroll-parallax/lib/utils/clamp.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/utils/clamp'>;
}
declare module 'react-scroll-parallax/lib/utils/getParallaxOffsets.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/utils/getParallaxOffsets'>;
}
declare module 'react-scroll-parallax/lib/utils/index.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/utils/index'>;
}
declare module 'react-scroll-parallax/lib/utils/isElementInView.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/utils/isElementInView'>;
}
declare module 'react-scroll-parallax/lib/utils/parseValueAndUnit.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/utils/parseValueAndUnit'>;
}
declare module 'react-scroll-parallax/lib/utils/propValidation.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/utils/propValidation'>;
}
declare module 'react-scroll-parallax/lib/utils/scaleBetween.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/utils/scaleBetween'>;
}
declare module 'react-scroll-parallax/lib/utils/testForPassiveScroll.js' {
  declare module.exports: $Exports<'react-scroll-parallax/lib/utils/testForPassiveScroll'>;
}
declare module 'react-scroll-parallax/postcss.config.js' {
  declare module.exports: $Exports<'react-scroll-parallax/postcss.config'>;
}
declare module 'react-scroll-parallax/src/components/Parallax.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/components/Parallax'>;
}
declare module 'react-scroll-parallax/src/components/ParallaxBanner.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/components/ParallaxBanner'>;
}
declare module 'react-scroll-parallax/src/components/ParallaxProvider.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/components/ParallaxProvider'>;
}
declare module 'react-scroll-parallax/src/index.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/index'>;
}
declare module 'react-scroll-parallax/src/libs/ParallaxController.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/libs/ParallaxController'>;
}
declare module 'react-scroll-parallax/src/utils/clamp.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/utils/clamp'>;
}
declare module 'react-scroll-parallax/src/utils/getParallaxOffsets.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/utils/getParallaxOffsets'>;
}
declare module 'react-scroll-parallax/src/utils/index.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/utils/index'>;
}
declare module 'react-scroll-parallax/src/utils/isElementInView.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/utils/isElementInView'>;
}
declare module 'react-scroll-parallax/src/utils/parseValueAndUnit.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/utils/parseValueAndUnit'>;
}
declare module 'react-scroll-parallax/src/utils/propValidation.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/utils/propValidation'>;
}
declare module 'react-scroll-parallax/src/utils/scaleBetween.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/utils/scaleBetween'>;
}
declare module 'react-scroll-parallax/src/utils/testForPassiveScroll.js' {
  declare module.exports: $Exports<'react-scroll-parallax/src/utils/testForPassiveScroll'>;
}
declare module 'react-scroll-parallax/stories/Element/Element.js' {
  declare module.exports: $Exports<'react-scroll-parallax/stories/Element/Element'>;
}
declare module 'react-scroll-parallax/stories/Parallax/Parallax.stories.js' {
  declare module.exports: $Exports<'react-scroll-parallax/stories/Parallax/Parallax.stories'>;
}
declare module 'react-scroll-parallax/stories/ParallaxBanner/ParallaxBanner.stories.js' {
  declare module.exports: $Exports<'react-scroll-parallax/stories/ParallaxBanner/ParallaxBanner.stories'>;
}
