// flow-typed signature: 0c7bb64b9f0db9b3781fd2f247632ebe
// flow-typed version: <<STUB>>/to-snake-case_v^1.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-snake-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-snake-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-snake-case/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-snake-case/index' {
  declare module.exports: $Exports<'to-snake-case'>;
}
declare module 'to-snake-case/index.js' {
  declare module.exports: $Exports<'to-snake-case'>;
}
declare module 'to-snake-case/test/index.js' {
  declare module.exports: $Exports<'to-snake-case/test/index'>;
}
