// flow-typed signature: e54fe33b2a113c2bacbb129f9cc4d2df
// flow-typed version: <<STUB>>/why-did-you-update_vhttps://github.com/maicki/why-did-you-update.git/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'why-did-you-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'why-did-you-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'why-did-you-update/demo/src/index' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/deepDiff' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/defaultNotifier' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/getDisplayName' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/index' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/normalizeOptions' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/shouldInclude' {
  declare module.exports: any;
}

declare module 'why-did-you-update/nwb.config' {
  declare module.exports: any;
}

declare module 'why-did-you-update/src/deepDiff' {
  declare module.exports: any;
}

declare module 'why-did-you-update/src/defaultNotifier' {
  declare module.exports: any;
}

declare module 'why-did-you-update/src/getDisplayName' {
  declare module.exports: any;
}

declare module 'why-did-you-update/src/index' {
  declare module.exports: any;
}

declare module 'why-did-you-update/src/normalizeOptions' {
  declare module.exports: any;
}

declare module 'why-did-you-update/src/shouldInclude' {
  declare module.exports: any;
}

declare module 'why-did-you-update/tests/deepDiff-test' {
  declare module.exports: any;
}

declare module 'why-did-you-update/tests/index-test' {
  declare module.exports: any;
}

declare module 'why-did-you-update/tests/normalizeOptions-test' {
  declare module.exports: any;
}

declare module 'why-did-you-update/tests/wrapper-test' {
  declare module.exports: any;
}

declare module 'why-did-you-update/umd/why-did-you-update' {
  declare module.exports: any;
}

declare module 'why-did-you-update/umd/why-did-you-update.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'why-did-you-update/demo/src/index.js' {
  declare module.exports: $Exports<'why-did-you-update/demo/src/index'>;
}
declare module 'why-did-you-update/lib/deepDiff.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/deepDiff'>;
}
declare module 'why-did-you-update/lib/defaultNotifier.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/defaultNotifier'>;
}
declare module 'why-did-you-update/lib/getDisplayName.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/getDisplayName'>;
}
declare module 'why-did-you-update/lib/index.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/index'>;
}
declare module 'why-did-you-update/lib/normalizeOptions.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/normalizeOptions'>;
}
declare module 'why-did-you-update/lib/shouldInclude.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/shouldInclude'>;
}
declare module 'why-did-you-update/nwb.config.js' {
  declare module.exports: $Exports<'why-did-you-update/nwb.config'>;
}
declare module 'why-did-you-update/src/deepDiff.js' {
  declare module.exports: $Exports<'why-did-you-update/src/deepDiff'>;
}
declare module 'why-did-you-update/src/defaultNotifier.js' {
  declare module.exports: $Exports<'why-did-you-update/src/defaultNotifier'>;
}
declare module 'why-did-you-update/src/getDisplayName.js' {
  declare module.exports: $Exports<'why-did-you-update/src/getDisplayName'>;
}
declare module 'why-did-you-update/src/index.js' {
  declare module.exports: $Exports<'why-did-you-update/src/index'>;
}
declare module 'why-did-you-update/src/normalizeOptions.js' {
  declare module.exports: $Exports<'why-did-you-update/src/normalizeOptions'>;
}
declare module 'why-did-you-update/src/shouldInclude.js' {
  declare module.exports: $Exports<'why-did-you-update/src/shouldInclude'>;
}
declare module 'why-did-you-update/tests/deepDiff-test.js' {
  declare module.exports: $Exports<'why-did-you-update/tests/deepDiff-test'>;
}
declare module 'why-did-you-update/tests/index-test.js' {
  declare module.exports: $Exports<'why-did-you-update/tests/index-test'>;
}
declare module 'why-did-you-update/tests/normalizeOptions-test.js' {
  declare module.exports: $Exports<'why-did-you-update/tests/normalizeOptions-test'>;
}
declare module 'why-did-you-update/tests/wrapper-test.js' {
  declare module.exports: $Exports<'why-did-you-update/tests/wrapper-test'>;
}
declare module 'why-did-you-update/umd/why-did-you-update.js' {
  declare module.exports: $Exports<'why-did-you-update/umd/why-did-you-update'>;
}
declare module 'why-did-you-update/umd/why-did-you-update.min.js' {
  declare module.exports: $Exports<'why-did-you-update/umd/why-did-you-update.min'>;
}
