import { t } from '../utils/i18n/translate';

export const ERROR_CODES = {
  REQUIRED: 101,
  EMAIL_IS_INVALID: 102,
  MUST_BE_A_NUMBER: 103,
  TOO_SHORT: 104,
  PASSWORD_TOO_SHORT: 105,
  PASSWORDS_NOT_MATCH: 106,

  //CUSTOM
  EMAIL_IS_REQUIRED: 201,
  PASSWORD_IS_REQUIRED: 202,

  //API
  API: {
    UNEXPECTED_ERROR: 500,
    BAD_CREDENTIALS: 901,
  },
};

export const ERROR_MESSAGES = {
  [ERROR_CODES.REQUIRED]: t('ERROR.VALIDATION.REQUIRED'),
  [ERROR_CODES.EMAIL_IS_REQUIRED]: t('ERROR.VALIDATION.EMAIL.REQUIRED'),
  [ERROR_CODES.EMAIL_IS_INVALID]: t('ERROR.VALIDATION.EMAIL.INVALID'),
  [ERROR_CODES.PASSWORD_IS_REQUIRED]: t('ERROR.VALIDATION.PASSWORD.REQUIRED'),
  [ERROR_CODES.PASSWORD_TOO_SHORT]: t('ERROR.VALIDATION.PASSWORD.TOO_SHORT'),
  [ERROR_CODES.API.UNEXPECTED_ERROR]: t('ERROR.API.UNEXPECTED'),
  [ERROR_CODES.API.BAD_CREDENTIALS]: t('ERROR.API.BAD_CREDENTIALS'),
};
